export { useConnect } from "./stores/useConnect"
export { useCanister } from "./stores/useCanister"
export { useWallet } from "./stores/useWallet"
export { useBalance } from "./stores/useBalance"
export { useTransfer } from "./stores/useTransfer"
export { default as ConnectButton } from "./components/ConnectButton.svelte"
export { default as ConnectDialog } from "./components/ConnectDialog.svelte"
export { default as Connect2ICProvider } from "./Connect2ICProvider.svelte"
// export * from "./stores"
// export * from "./components"